name: domain
description: Domain module
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.19.1 <3.0.0"
  flutter: "3.7.1"

dependencies:
  device_info_plus: 8.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: 7.0.1
  foundation:
    path: ../foundation
  fpdart: 0.4.0
  freezed_annotation: 2.2.0
  get_it: 7.2.0
  json_annotation: 4.8.0
  json_serializable: 6.6.0
  project_linter:
    path: ../project_linter
  rxdart: 0.27.7
  shared_preferences: 2.0.17

dev_dependencies:
  analyzer: 5.4.0
  build_runner: 2.3.3
  freezed: 2.3.2
  mocktail: 0.3.0
  platform: 3.1.0
  test: 1.22.2

flutter:
