name: domain
description: Domain module
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: "3.0.5"

dependencies:
  device_info_plus: 4.0.1
  flutter:
    sdk: flutter
  foundation:
    path: ../foundation
  fpdart: 0.2.0
  freezed_annotation: 2.1.0
  get_it: 7.2.0
  project_linter:
    path: ../project_linter
  shared_preferences: 2.0.15

dev_dependencies:
  analyzer: 4.2.0
  build_runner: 2.2.0
  freezed: 2.1.0+1
  mocktail: 0.3.0
  platform: 3.1.0
  test: 1.21.4

flutter:
