name: foundation
description: Foundation module
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: "3.0.5"

dependencies:
  flutter:
    sdk: flutter
  fpdart: 0.2.0
  logging: 1.0.2
  project_linter:
    path: ../project_linter

dev_dependencies:
  flutter_test:
    sdk: flutter
  platform: 3.1.0

flutter:
