name: foundation
description: Foundation module
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.19.1 <3.0.0"
  flutter: "3.7.1"

dependencies:
  flutter:
    sdk: flutter
  fpdart: 0.4.0
  logging: 1.1.0
  project_linter:
    path: ../project_linter

dev_dependencies:
  flutter_test:
    sdk: flutter
  platform: 3.1.0

flutter:
