name: presentation
description: Presentation module
version: 1.0.0
author:
homepage: ' '

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  foundation:
    path: ../foundation
  domain:
    path: ../domain
  remote:
    path: ../remote

  cupertino_icons: ^1.0.2
  flutter_dotenv: 4.0.0-nullsafety.0
  flutter_bloc: 7.0.0
  freezed_annotation: 0.14.1
  get_it: 6.0.0
  google_fonts: 2.0.0
  intl: 0.17.0
  stacked_themes: 0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: 1.3.0
  bloc_test: 8.0.0
  build_runner: 1.12.2
  freezed: 0.14.1+1
  mockito: 5.0.3
  pedantic: 1.11.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/images/
