name: _RAW_NAME_
description: ' '
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: "3.3.0"

dependencies:
  flutter:
    sdk: flutter

  presentation:
    path: modules/presentation
  project_linter:
    path: modules/project_linter

dev_dependencies:
  change_app_package_name: 1.1.0

flutter:
  uses-material-design: true